### PR TITLE
Linux create_package.sh script

### PR DESCRIPTION
**Pull request by ironictoo**
I converted the create_package script to bash, and added a few things needed for a linux package (create a .deb package, grab the appropriate linux libraries, etc).

It works on my system (Ubuntu 20.04.2 LTS) but I haven't done testing on other systems. I am willing to help with linux specific updates to cmake as well if you are interested (I had to make edits to get it to build on my system).

### CODE REVIEW

**Comment by jkfindeisen** [comment]
Sure, you could insert the linux specific updates to cmake in your linux_build branch, or have you already?

**Comment by ironictoo** [comment]
I'll add the cmake edits to the branch on Monday

**Comment by ironictoo** [comment]
I've updated my branch with all the linux specific edits I have. The main thing is CUBLAS linking from the main CMakeFile, but I also added two convenience scripts. One just runs the pip command to install the python wheel file, and the other runs all the boosts tests to make sure everything is working after build.

**Comment by jkfindeisen** [comment]
Thanks. I'll test it here.

**Comment by jkfindeisen** [comment]
In a few days there will be a new release. The Linux package script won't be part of it, but afterwards I'll look a bit more at it. If you want to run "all the boosts tests to make sure everything is working after build." just do "make test". It runs the tests automatically. I have again a Linux computer with all needed libraries here now, so I can test this PR.

**Comment by ironictoo** [comment]
These changes were included in #94 so I'm going to close this.

**Pull request closed without merging**
